"""Serves the 2 committed fallback IFC fixtures (backend/app/data/fallback_models/*.ifc)
generated by fallback_model_generator.py. Parsed results are cached in-process per
worker so repeated requests don't re-run ifcopenshell.geom on every call."""

import os
import functools
from typing import Optional

from app.services import bim_service

FALLBACK_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "fallback_models")

FALLBACK_META = [
    {"id": "metro-general-hospital", "name": "Metro General Hospital",
     "description": "8-storey, 3-wing hospital complex", "category": "healthcare"},
    {"id": "riverside-residential-complex", "name": "Riverside Residential Complex",
     "description": "4 residential towers (15 storeys) on a shared podium", "category": "residential"},
]
_META_BY_ID = {m["id"]: m for m in FALLBACK_META}
LARGEST_FALLBACK_ID = "riverside-residential-complex"


@functools.lru_cache(maxsize=2)
def _load_bytes(model_id: str) -> bytes:
    with open(os.path.join(FALLBACK_DIR, f"{model_id}.ifc"), "rb") as f:
        return f.read()


@functools.lru_cache(maxsize=2)
def _parsed(model_id: str) -> dict:
    file_bytes = _load_bytes(model_id)
    bim_data = bim_service.parse_ifc_geometry(file_bytes, f"{model_id}.ifc")
    mesh_result = bim_service.parse_ifc_for_3d(file_bytes, f"{model_id}.ifc")
    return {
        "bim_data": bim_data,
        "meshes": mesh_result.get("meshes", []) if mesh_result.get("success") else [],
    }


def list_fallback_models() -> list:
    models = []
    for meta in FALLBACK_META:
        parsed = _parsed(meta["id"])
        models.append({
            **meta,
            "total_elements": parsed["bim_data"].get("total_elements", 0),
            "storeys": len(parsed["bim_data"].get("storeys", [])),
        })
    return models


def get_fallback_model(model_id: str) -> Optional[dict]:
    if model_id not in _META_BY_ID:
        return None
    return _parsed(model_id)


def get_fallback_model_bytes(model_id: str) -> Optional[bytes]:
    if model_id not in _META_BY_ID:
        return None
    return _load_bytes(model_id)
