"""
Grounding check for the agentic tool-calling copilot (app/ai/agent_copilot.py).

The agent's system prompt instructs it to base domain answers on live tool
output, but nothing previously verified that the final reply actually stuck
to what the tools returned. This runs a fast secondary classifier comparing
the reply against the concatenated tool output and flagging replies that
assert project-specific facts not present in it.

Deliberately runs on a different model family (openai/gpt-oss-120b) than the
model being checked: the reply being verified was generated by a Groq Llama
model (agent_copilot.py's llama-3.3-70b-versatile, also what nemo_rails.py
uses) — checking it with that same model risks sharing its blind spots. Both
still run on Groq, so this doesn't gain an independent quota pool, but it
does gain an independent "opinion".

This is a soft signal, not a hard block: callers route a failed check into
HITL review (see app/core/hitl.py: check_agent_reply) rather than refusing
the response outright, since a false positive here would block a correct
answer instead of just flagging it for a human.
"""
import asyncio
import logging

from app.ai.groq_client import client as groq_client, call_with_retry

logger = logging.getLogger("civilai.grounding")

_MODEL = "openai/gpt-oss-120b"
_MAX_CONTEXT_CHARS = 8000

GROUNDING_CAVEAT = (
    "\n\n*This response could not be fully verified against the underlying project "
    "data — please double-check the figures above before acting on them.*"
)

_CLASSIFIER_PROMPT = """You are a fact-checking classifier for CivilAI, a construction \
project management AI. You will be shown TOOL OUTPUT (real data fetched live from a \
database) and a REPLY generated from it.

Judge whether the REPLY is grounded in the TOOL OUTPUT: every project-specific number, \
date, name, or status the REPLY states must be traceable to the TOOL OUTPUT. General \
domain knowledge, standards references (OSHA/FIDIC/ACI/etc.), and reasoning/recommendations \
built on top of the data are fine and do not count against grounding.

Reply with ONE word only:
GROUNDED    - all project-specific facts in the REPLY are supported by the TOOL OUTPUT
UNGROUNDED  - the REPLY states project-specific facts, numbers, or names not present in \
              the TOOL OUTPUT"""


def _build_tool_context(tool_steps: list[dict]) -> str:
    # Steps with blank output are dropped rather than included as a bare
    # "[tool_name]" header — otherwise a tool that returned nothing would
    # still produce non-empty formatted context and skip the empty-output check below.
    parts = [
        f"[{step.get('tool', 'unknown_tool')}]\n{step['output'].strip()}"
        for step in tool_steps
        if (step.get("output") or "").strip()
    ]
    return "\n\n".join(parts)[:_MAX_CONTEXT_CHARS]


async def check_grounding(reply: str, tool_steps: list[dict]) -> tuple[bool, str]:
    """
    Classify whether `reply` is grounded in the tool outputs that produced it.

    Returns (is_grounded, reason). Skips the check (grounded=True) when no
    tools were called or all tool outputs were empty — nothing to compare
    against, and whether a tool *should* have been called is a separate
    tool-use-appropriateness concern, not a grounding one. Fails open on
    classifier errors, consistent with the other guardrail layers — an
    outage should not queue every reply for review.
    """
    if not tool_steps:
        return True, "no_tools_called"

    tool_context = _build_tool_context(tool_steps)
    if not tool_context.strip():
        return True, "empty_tool_output"

    try:
        result = await asyncio.get_event_loop().run_in_executor(
            None,
            lambda: call_with_retry(lambda: groq_client.chat.completions.create(
                model=_MODEL,
                messages=[
                    {"role": "system", "content": _CLASSIFIER_PROMPT},
                    {"role": "user", "content": f"TOOL OUTPUT:\n{tool_context}\n\nREPLY:\n{reply}"},
                ],
                max_tokens=1024,
                temperature=0,
                reasoning_effort="low",
            )),
        )
        label = result.choices[0].message.content.strip().upper()
        if label.startswith("UNGROUNDED"):
            return False, "Reply contains claims not supported by tool output"
        return True, "grounded"
    except Exception as exc:
        logger.warning("Grounding check unavailable, failing open | error=%s", exc)
        return True, "check_unavailable"
